### ISSUE TITLE
Seg fault when loading trajectories.

### ISSUE THREAD

**Issue by icecube45** [JacisNonsense/Pathfinder#13]
Hello again, 
everything is working flawlessly in the c++ version, except loading of trajectories.
I've tried loading both a csv and binary file, and each time, once pathfinder_deserialize (or pathfinder_deserialize_csv) is called, a segmentation fault occurs. This happens with the example code provided as well.

Any help would be appreciated for solving this issue

**Comment by gbear605** [comment]
I also experience this with the Java version.

**Comment by JacisNonsense** [comment]
Can you send me the generated .csv file? A gist will do.

**Comment by icecube45** [comment]
https://gist.github.com/icecube45/9b0d92e1c36b05a0c0b9fffd9c098245

**Comment by JacisNonsense** [comment]
@icecube45,
What waypoints are you generating the trajectory with?

**Comment by icecube45** [comment]
@JacisNonsense This was generated with the points of 
`		{15,0,0},
		{69.32,49.26,0},
		{127,14.07,util::d2r(-60)}`

And a swerve modifier with a 20in square for the wheelbase

**Comment by icecube45** [comment]
@JacisNonsense I've found my issue - I was under allocating the trajectory for loading into.

**Comment by JacisNonsense** [comment]
@icecube45 ahh, that'd do it. I'm glad you found your issue, I was just about to say I couldn't reproduce it.

**Comment by icecube45** [comment]
@JacisNonsense this might be worthwhile to put in the documentation - I'm going to have to play with it a bit more as on the roboRio itself the issue persists, whereas underallocation solved it in my testing environment. Perhaps I'm allocating too large now, I might need to reduce my samples.

**Comment by JacisNonsense** [comment]
The number of points you need to allocate depends on a lot of different factors. Typically, instead of calling `malloc()`, I will instead use a static array to hold the generated points, e.g. `static Segment mySegs[1024]`. As for overallocation, this depends on your platform, and what memory space is available on the system.
