### ISSUE TITLE
Build fails on ubuntu 17.04

### ISSUE THREAD

**Issue by NoahGleason** [JacisNonsense/Pathfinder#15]
I cloned the repo and ran ./gradlew build, and it failed with the message:
```
 FAILURE: Build failed with an exception.

* Where:
Script '/media/LinHDD/Documents/Pathfinder/Pathfinder-Java/jni.gradle' line: 38

* What went wrong:
A problem occurred configuring project ':Pathfinder-Java'.
> Exception thrown while executing model rule: pathfinderjava(org.gradle.nativeplatform.NativeLibrarySpec) { ... } @ Pathfinder-Java/jni.gradle line 37, column 9
   > No such property: isArm for class: org.gradle.nativeplatform.NativeLibrarySpec

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.976 secs
```
Output of running uname -a:
`Linux noah-MS-7922 4.10.0-20-generic #22-Ubuntu SMP Thu Apr 20 09:22:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Output of java -version:
```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-4-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```
And [here's the ouput](https://pastebin.com/ZHfwvjkn) of `./gradlew build --stacktrace --info --debug`.
Also, when I try to run a program using Pathfinder, with the compiled libraries checked out from github, I get:
```
Platform: /Linux/amd64/
Exception in thread "main" java.lang.UnsatisfiedLinkError: no pathfinderjava in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jaci.pathfinder.PathfinderJNI.loadLibrary(PathfinderJNI.java:74)
	at jaci.pathfinder.PathfinderJNI.<clinit>(PathfinderJNI.java:27)
	at jaci.pathfinder.Pathfinder.generate(Pathfinder.java:46)
	at org.usfirst.frc.team449.pathgen.Pathgen.main(Pathgen.java:140)
```
Tell me if you need any more info!

**Comment by JacisNonsense** [comment]
Are you on the `master` branch or the `v2` branch? V2 has not started work for the Java component just yet

**Comment by NoahGleason** [comment]
master, most recent commit is `9473cba Add spline and trajectory impl`

**Comment by JacisNonsense** [comment]
Sorry about that, looks like I accidentally pushed to master. Run `git checkout 72ff7ba` and try building again. I'll revert master when I can

**Comment by NoahGleason** [comment]
That worked, thanks for your help! (also, looking at commit names, does V2 have support for shifting? That's awesome!)

**Comment by JacisNonsense** [comment]
V2 does indeed have support for shifting gearboxes so far. There are still some little things to iron out (it flutters a bit on some paths), but the support is there
