### ISSUE TITLE
Error:No such property: isArm for class: org.gradle.nativeplatform.NativeLibrarySpec

### ISSUE THREAD

**Issue by johansu** [JacisNonsense/Pathfinder#16]
On 64-bit Windows IntelliJ IDEA 2017.1, jdk1.8.0_131.  Import and build fails (clone of master) with missing isArm gradle property.  Issue with repository or my machine setup?

**Comment by JacisNonsense** [comment]
See #15

**Comment by bortonjeff** [comment]
This issue still exists in the latest release.  Do we still need to pull from 72ff7ba?   Trying to compile on windows 10 64 bit with jdk1.8.0_131.  The gradle script fails.

**Comment by JacisNonsense** [comment]
Yes, please checkout from that commit. I'll reset master at some point but at the moment this project is on the backburner
