### ISSUE TITLE
Excluding Area from Generated Path

### ISSUE THREAD

**Issue by roshanr10** [JacisNonsense/Pathfinder#20]
Is there a way to avoid going into a certain area built into Pathfinder?

Say I want to go around the switch in my profile, is that easily doable, within the library, or should I resort to just setting points around the switch with a large enough radius?

**Comment by JacisNonsense** [comment]
The best way to make this happen is to add a bunch of waypoints around the perimeter of where you don't want to be

**Comment by roshanr10** [comment]
Okay, just wanted to clarify if there was a better way. Thanks!
