### ISSUE TITLE
When building, cant find .maven.cred file

### ISSUE THREAD

**Issue by team2053tigertronics** [JacisNonsense/Pathfinder#21]
When building on Windows, build fails with a file not found exception. Here is a log file of the build command. This was freshly cloned.

I see an error about an invalid cookie header but Im not sure what else could be causing the error.

[pathfinderlog.txt](https://github.com/JacisNonsense/Pathfinder/files/1619635/pathfinderlog.txt)

**Comment by JacisNonsense** [comment]
There are some published releases on maven at http://dev.imjac.in/maven

I'll get to fixing this issue shortly
