### ISSUE TITLE
2018 Issues

### ISSUE THREAD

**Issue by granjef3** [JacisNonsense/Pathfinder#22]
Can't get build working on my windows 10 machine to test recent commits (probably my fault), fails when compiling the JNI pathfinder lib.

I've tried the 2017 1.5 and 1.4 builds, which deploy fine but fail with a UnsatisfiedLinkError for the pathfinder JNI lib.

Is there a way to get Pathfinder running on a 2018 bot yet?

**Comment by JacisNonsense** [comment]
See the README here: https://github.com/JacisNonsense/Pathfinder#part-of-the-first-robotics-competition

**Comment by granjef3** [comment]
I'm not using gradleRIO, is it necessary?

I put the 1.5 jar into the wpilib userLibs directory. It's being included in the FRCUserProgram jar, but the robot program quits when it can't find the compiled JNI library.

**Comment by ankithu** [comment]
Hi, we're having the same issue. We put pathfinder jar file in the wpilib/user directory. It compiles fine, but during execution, it throws an UnsatisfiedLinkError when PathFinderJNI tries to load the library. We are compiling on Windows 10 with the 2018 development environment. We don't currently use GradleRIO; is there a way to solve this without adding any plugins? Thanks for the help.

**Comment by JacisNonsense** [comment]
If you're not using GradleRIO, you must download [this](http://dev.imjac.in/maven/jaci/pathfinder/Pathfinder-Java/1.8/Pathfinder-Java-1.8.jar) manually and copy  into `~/wpilib/user/java/lib`.

You also have to download [this](http://dev.imjac.in/maven/jaci/pathfinder/Pathfinder-JNI/1.8/Pathfinder-JNI-1.8-athena.zip), extract it, and place `libpathfinder.so` into `~/wpilib/user/java/lib`

**Comment by ankithu** [comment]
Thank you, this fixed our problem!
