### ISSUE TITLE
Building Java for Windows

### ISSUE THREAD

**Issue by duane701** [JacisNonsense/Pathfinder#29]
How do I compile so that I can use the library to run a program on Windows?

The primary error is

    No C compiler for Binary (shared library 'pathfinder:any64:sharedlibrary') with Toolchain clang on Platform any64. Skipping build.

Does the build require clang? I installed msys so that I have gcc. 

What are the requirements and instructions for building the library so that I can build and run a program on Windows?

Thanks

**Comment by JacisNonsense** [comment]
On windows, you need to have Visual Studio installed in order to build native libraries with Gradle

**Comment by duane701** [comment]
I've now installed visual studio (I'll have to work out which installer I ran if it's important).

After building I get
    LINK: fatal error LNK1104: cannot open file `kernel32.lib`

The error is from `Pathfinder-Core:linkPathfinderAny64SharedLibrary`. 

The program we have developed uses Java which of course uses the shared library to run. 

I'm on a 64-bit system. 

Thoughts?

**Comment by JacisNonsense** [comment]
This sounds like a problem during installation. Check that you've installed the windows desktop C++ SDK, and that you did indeed install the 64 bit version.

**Comment by duane701** [comment]
same same 👎 

I installed Visual Studio Community 2017 with "Desktop development with C++" and "Universal Windows Platform Development".

I've tried using the command prompt from "Developer Command Prompt for VS 2017" and "x64 Native Tools Command Prompt for VS 2017". Same error under both conditions. 

Thanks for any tips. 

(I'm not a Windows person. The library works great on the Mac.)

**Comment by duane701** [comment]
It sounds like other people are able to compile Pathfinder-Tool on Windows. I would appreciate any tips that might help me work out where I am running into a problem.

**Comment by duane701** [comment]
`C:\Program Files (x86)\Windows Kits\10\bin\Lib\winv6.3\um\x64` does not exist, starting at `Lib\winv6.3\um\x64`. That is there is no `Lib` directory at all.

* How is this directory supposed to be installed?
* Does Gradle need to be updated?
* Are there options to set for Gradle?

Thanks

**Comment by duane701** [comment]
The correct path seems to be `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\ucrt\x64` at least that's where `kernel32.lib` is located. 

Why is gradle searching in this other location?

**Comment by dkt01** [comment]
I was able to build in Windows 10 with the Visual Studio 2017 build tools, but I had to download an additional Windows 10 SDK version using the installer.  For some reason the default SDK wouldn't link correctly.  Think it was the version just before the latest SDK version that worked correctly.

**Comment by virtuald** [comment]
I was able to build in Windows 7 with the Visual Studio 2015 build tools, with no SDK installed.

**Comment by JacisNonsense** [comment]
Gradle discovers the directory for VS based on the installation of vswhere with VS2017, since Gradle 4.4. That may be pointing to the wrong location. Can you run vswhere manually?

**Comment by duane701** [comment]
`>vswhere
'vswhere' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by duane701** [comment]
I tried on another computer (control variables) with the same result.
Following @dkt01, I installed the additional SDKs one at a time. The requirement appears to be "Windows 10 SDK (10.0.14393.0)" in order get linking to work correctly.

Now that the library is compiled, I'll see if I can run the app.

**Comment by duane701** [comment]
My app compiled and executed. Closing this issue.

**Comment by JacisNonsense** [comment]
Thanks for looking into it, it's a particularly hard issue to reproduce. Glad you found the dep required
