### ISSUE TITLE
Native error in path generation

### ISSUE THREAD

**Issue by tkdberger** [JacisNonsense/Pathfinder#31]
When I try to call path generation (code [here](https://github.com/BHSSFRC/3494_2018_repo/tree/feature/pathfinder-tests), mainly Robot.java and PathBuilder.java), there's some form of native code error. The Driver Station consistently gives the same log:

```
 # 
 # A fatal error has been detected by the Java Runtime Environment: 
 # 
 #  SIGSEGV (0xb) at pc=0xab410158, pid=4602, tid=0xb5370470 
 # 
 # JRE version: OpenJDK Runtime Environment (8.0_131-b57) (build 1.8.0_131-b57) 
 # Java VM: OpenJDK Client VM (25.131-b57 mixed mode, Evaluation linux-aarch32 ) 
 # Problematic frame: 
 # C  [libpathfinderjava.so+0x6158]  pf_trajectory_fromSecondOrderFilter+0x88 
 # 
 # Core dump written. Default location: //core or core.4602 (max size 2048 kB). To ensure a full core dump, try "ulimit -c unlimited" before starting Java again 
 # 
 # An error report file with more information is saved as: 
 # /tmp/hs_err_pid4602.log 
 # 
 # If you would like to submit a bug report, please visit: 
 #   http://www.azulsystems.com/support/ 
 # The crash happened outside the Java Virtual Machine in native code. 
 # See problematic frame for where to report the bug. 
 #
```

**Comment by JacisNonsense** [comment]
This usually shows that the path you're trying to generate is invalid. [This](https://github.com/BHSSFRC/3494_2018_repo/blob/feature/pathfinder-tests/src/main/java/org/usfirst/frc/team3494/robot/commands/auto/PathBuilder.java#L38-L42) is one such path, since angles are relative to the positive X axis, trying to go from Y=0 to Y=1 @ 0deg, without any translation in the X direction, this path isn't possible.

**Comment by tkdberger** [comment]
Alright.

That solves my issue, but out of curiosity, is there a tool anywhere to make images like the ones in README?

**Comment by JacisNonsense** [comment]
I use Tableau with the .csv files generated by pathfinder, but you can also check out Vannaka's Motion Profile Generator GUI for Pathfinder [here](https://github.com/vannaka/Motion_Profile_Generator) which many find useful
