### ISSUE TITLE
Crash when reading CSV files

### ISSUE THREAD

**Issue by GaganBhat** [JacisNonsense/Pathfinder#32]
When I try reading CSV files from the roboRio using Pathfinder.readFromCSV(), the code crashes on the Rio.

Here's the code within the constructor of the class.

![image](https://user-images.githubusercontent.com/25236969/35950375-d69d4e98-0c3b-11e8-94e9-59e5ea1ca129.png)

exists() returns true and so does canRead(). The absolute path is also correct. When I comment out line 32, the error disappears. 

Here's the error from the roboRio console

` true 
 /home/lvuser/StraightForward_left.csv 
 true 
 # 
 # A fatal error has been detected by the Java Runtime Environment: 
 # 
 #  SIGSEGV (0xb) at pc=0xb6d795b0, pid=14157, tid=0xb52b6470 
 # 
 # JRE version: OpenJDK Runtime Environment (8.0_131-b57) (build 1.8.0_131-b57) 
 # Java VM: OpenJDK Client VM (25.131-b57 mixed mode, Evaluation linux-aarch32 ) 
 # Problematic frame: 
 # C  [libc.so.6+0x345b0] 
 # 
 # Core dump written. Default location: //core or core.14157 (max size 2048 kB). To ensure a full core dump, try "ulimit -c unlimited" before starting Java again 
 # 
 # An error report file with more information is saved as: 
 # /tmp/hs_err_pid14157.log 
 # 
 # If you would like to submit a bug report, please visit: 
 #   http://www.azulsystems.com/support/ 
 # The crash happened outside the Java Virtual Machine in native code. 
 # See problematic frame for where to report the bug. 
 # `

Thanks in Advance!

**Comment by roshanr10** [comment]
Think you could link the trajectory you’re trying to import? I’ve had issues when the trajectory wasn’t mathematically accurate... have you tested a simple drive straight trajectory?

**Comment by GaganBhat** [comment]
[StraightForward_left.txt](https://github.com/JacisNonsense/Pathfinder/files/1705479/StraightForward_left.txt)

Here is the csv file (converted to txt so that github accepts it.)

**Comment by roshanr10** [comment]
Was this created using Vannaka’a generator GUI? I think you’re using the “SRX” profile they export... you need to use the “detailed” profile for it to be able to import into Pathfinder code using the read function.

**Comment by GaganBhat** [comment]
Alright, thanks a ton for that, I will try that right now! And yes, I did use Vannaka's generator GUI xD

**Comment by GaganBhat** [comment]
Thanks for letting me know, the error doesn't occur anymore and everything functions normally =)
