### ISSUE TITLE
Angle orientations incorrect

### ISSUE THREAD

**Issue by minglethepringle** [JacisNonsense/Pathfinder#47]
Here's the issue I opened; they said it's a Pathfinder bug.

https://github.com/Endoman123/motion-profile-generator/issues/11

TL;DR: 90 degrees and -90 degrees point in the same direction, 150 degrees points in the wrong direction, angles are just wack overall

**Comment by JacisNonsense** [comment]
I've replied in the thread you've linked. This is a constraint on how Pathfinder functions.
