### ISSUE TITLE
FRC-Beta Compilation Error

### ISSUE THREAD

**Issue by codeNinjaDev** [JacisNonsense/Pathfinder#58]
Legacy Pathfinder does not compile with the beta version of wpilib. I have included the json via the wpilib command palette (Vendor Dependencies). 
I am on Windows 10 with JDK 11.
Here are the logs: 

`FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\kidco\Documents\Alpha-Beta\build.gradle' line: 59

* What went wrong:
Could not determine the dependencies of task ':jar'.
> Could not resolve all files for configuration ':compile'.
   > Could not find jaci.pathfinder:FRCSupport:2019.1.10.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/jaci/pathfinder/FRCSupport/2019.1.10/FRCSupport-2019.1.10.pom
       - https://repo.maven.apache.org/maven2/jaci/pathfinder/FRCSupport/2019.1.10/FRCSupport-2019.1.10.jar
       - file:/C:/Users/Public/frc2019/maven/jaci/pathfinder/FRCSupport/2019.1.10/FRCSupport-2019.1.10.pom
       - file:/C:/Users/Public/frc2019/maven/jaci/pathfinder/FRCSupport/2019.1.10/FRCSupport-2019.1.10.jar
       - http://first.wpi.edu/FRC/roborio/maven/release/jaci/pathfinder/FRCSupport/2019.1.10/FRCSupport-2019.1.10.pom
       - http://first.wpi.edu/FRC/roborio/maven/release/jaci/pathfinder/FRCSupport/2019.1.10/FRCSupport-2019.1.10.jar
       - https://dev.imjac.in/maven/jaci/pathfinder/FRCSupport/2019.1.10/FRCSupport-2019.1.10.pom
       - https://dev.imjac.in/maven/jaci/pathfinder/FRCSupport/2019.1.10/FRCSupport-2019.1.10.jar
       - http://wpimirror.imjac.in/m2/release/jaci/pathfinder/FRCSupport/2019.1.10/FRCSupport-2019.1.10.pom
       - http://wpimirror.imjac.in/m2/release/jaci/pathfinder/FRCSupport/2019.1.10/FRCSupport-2019.1.10.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 12s
The terminal process terminated with exit code: 1`

**Comment by Daltz333** [comment]
My team is part of the beta Reproduction steps on Beta 2.

```
1. Create blank Java project in VSCode
2. Install Pathfinder via "manage vendor libraries'
3. Compile
4. Observe
```

Get the following warning when compiling

```
Error loading Vendor File C:\Users\daltz\OneDrive\Documents\Code Projects\frc-66-vscode-example\vendordeps\PathfinderOLD.json
```

**Comment by JacisNonsense** [comment]
Yea, this is part a problem with the Pathfinder build setup and partly on GradleRIO (which has been fixed). I'll start a fix on this as soon as I can, but that's likely not until Monday

**Comment by JacisNonsense** [comment]
This should be fixed now, go ahead and grab Beta 4 and try downloading a new vendordeps file from https://dev.imjac.in/maven/jaci/pathfinder/PathfinderOLD-latest.json
