### ISSUE TITLE
Gyro Affecting Paths

### ISSUE THREAD

**Issue by JavaCafe01** [JacisNonsense/Pathfinder#64]
Alright, so Pathfinder was working perfectly on our old bot, which had cims and an Analog Devices Gyro. Our new bot contains Neos and a Nav-X Micro. After adjusting all the values, the robot didn't even follow the path. However, once I took out the gyro code, The robot followed the path pretty well. So I isolated the problem to the Nav-X gyro. Should I use `getAngle()` (Continous degrees) or `getYaw()` (180 to -180)? And should I put a negative in the calculations to reverse the gyro addressed in the problem [here](https://wpilib.screenstepslive.com/s/currentCS/m/84338/l/1021631-integrating-path-following-into-a-robot-program)? Thanks a lot, this is the first year our team is using your library.

**Comment by JacisNonsense** [comment]
Either `GetAngle` or `GetYaw` should work just fine. I can't provide any specific support for technical problems with hardware, check the gyro is exporting data correctly
