### ISSUE TITLE
Throwing IOException on file errors breaks users code

### ISSUE THREAD

**Issue by sciencewhiz** [JacisNonsense/Pathfinder#65]
While throwing an IOException added in commit 6813db0716995a93ed1811775b7ff518387aa1cb is the "right" thing to do, it breaks users code and examples because it requires that the user catch the exception. 

It would be less breaking to change it to a runtime exception now, so that code crashes but with a useful stack trace, and then next year make it an IOException.

**Comment by JacisNonsense** [comment]
This isn't an issue, users can choose to update or roll back their vendordeps if they are not prepared to deal with the changes.
