### ISSUE TITLE
Citing Pathfindfer

### ISSUE THREAD

**Issue by rafaelrojasmiliani** [JacisNonsense/Pathfinder#69]
First, I would like to congratulate the contributors of this repository. It is a wonderful work.

I would like to cite Pathfinder in a paper with a review of motion planning libraries. 
Is there a paper that I can cite with a description of this library or a representative application it?

**Comment by JaciBrunning** [comment]
Hi Rafael,

Thanks for the kind words! You can cite Pathfinder using the below formats. Unfortunately I don't have a paper out on Pathfinder; this repository is likely the closest resource to what you're looking for.

```bibtex
@misc{Pathfinder2016,
  author = {Brunning, Jacinta R},
  title = {Pathfinder},
  year = {2016},
  publisher = {GitHub},
  journal = {GitHub Repository},
  url = {https://github.com/JaciBrunning/Pathfinder}
}
```

**APA**: Brunning, J. R. (2016). Pathfinder. In GitHub Repository. GitHub. https://github.com/JaciBrunning/Pathfinder
**Chicago**: Brunning, Jacinta R. 2016. “Pathfinder.” GitHub Repository. GitHub. https://github.com/JaciBrunning/Pathfinder.
**IEEE**: [1] J. R. Brunning, “Pathfinder,” GitHub Repository. GitHub, 2016. [Online]. Available: https://github.com/JaciBrunning/Pathfinder
**Vancouver**: 1. Brunning JR. Pathfinder [Internet]. GitHub Repository. GitHub; 2016. Available from: https://github.com/JaciBrunning/Pathfinder

I'd also recommend citing Team 254's TrajectoryLib, of which Pathfinder was based on. https://github.com/Team254/TrajectoryLib

**Comment by rafaelrojasmiliani** [comment]
Thank you very much @JaciBrunning . I will use that reference. Really, I think that this kind of works are very useful and not easy to do, I would be glad to read any paper with an application of the library.
